# Node.js with Angular
# Build a Node.js project that uses Angular.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- develop

pool:
  'piranema-build'

steps:

- task: NodeTool@0
  displayName: 'Use Node 12.14'
  inputs:
    versionSpec: 12.14

- task: Npm@1
  inputs:
    command: 'install'
  displayName: 'npm install -g @angular/cli'

#- script: |
#    npx ng test --watch=false --code-coverage
#  displayName: 'perform unit tests'
#  continueOnError: 'true'

- task: Npm@1
  displayName: 'build angular'
  inputs:
    command: 'custom'
    customCommand: 'run build --configuration=production --base-href=/anp-nsimp-web/'

#- task: Npm@1
#  displayName: 'build angular war'
#  inputs:
#    command: 'custom'
#    customCommand: 'run build:war'

- task: ArchiveFiles@2
  inputs:
    rootFolderOrFile: '$(Build.SourcesDirectory)/dist'
    includeRootFolder: false
    archiveType: 'zip'
    archiveFile: '$(Build.ArtifactStagingDirectory)/anp-nsimp-web.zip'
#    archiveFile: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'
    replaceExistingArchive: true

- task: CopyFiles@2
  inputs:
    SourceFolder: $(Build.ArtifactStagingDirectory)
    contents: '**/*.zip'
    targetFolder: $(Build.ArtifactStagingDirectory)

- task: PublishBuildArtifacts@1
  inputs:
    pathToPublish: $(Build.ArtifactStagingDirectory)
    artifactName: MyBuildOutputs